name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: 🔍 Check if secret is passed
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}" ]; then
            echo "❌ Secret is empty or missing!"
            exit 1
          else
            echo "✅ Secret exists and is being picked up."
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          action: "upload"
          app_location: Icecream-website-main/Icecream-website-main
          output_location: ""
          skip_app_build: true
e
